/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CSlugIndexRouteImport } from './routes/c.$slug.index'
import { Route as CSlugPProductSlugRouteImport } from './routes/c.$slug.p.$productSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugIndexRoute = CSlugIndexRouteImport.update({
  id: '/c/$slug/',
  path: '/c/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugPProductSlugRoute = CSlugPProductSlugRouteImport.update({
  id: '/c/$slug/p/$productSlug',
  path: '/c/$slug/p/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/c/$slug/p/$productSlug': typeof CSlugPProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$slug': typeof CSlugIndexRoute
  '/c/$slug/p/$productSlug': typeof CSlugPProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/c/$slug/p/$productSlug': typeof CSlugPProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/c/$slug/' | '/c/$slug/p/$productSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/c/$slug' | '/c/$slug/p/$productSlug'
  id: '__root__' | '/' | '/c/$slug/' | '/c/$slug/p/$productSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CSlugIndexRoute: typeof CSlugIndexRoute
  CSlugPProductSlugRoute: typeof CSlugPProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/': {
      id: '/c/$slug/'
      path: '/c/$slug'
      fullPath: '/c/$slug/'
      preLoaderRoute: typeof CSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/p/$productSlug': {
      id: '/c/$slug/p/$productSlug'
      path: '/c/$slug/p/$productSlug'
      fullPath: '/c/$slug/p/$productSlug'
      preLoaderRoute: typeof CSlugPProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CSlugIndexRoute: CSlugIndexRoute,
  CSlugPProductSlugRoute: CSlugPProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
